project:
  type: website

website:
  title: "Jazlynn Hall"
  navbar:
    left:
      - file: about.qmd
        text: "About"
      - file: projects.qmd
        text: "Projects"
      - file: CV_JazlynnHall_241212.pdf
        text: "CV"
      - file: TeachingDemo.qmd
        text: 'Teaching Demonstration'
      - file: lectureslides.pdf
        text: 'Lecture Slides'
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

